# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS


TWITTER_API_KEY: dx3jDEqhSSPMkOxurdjYD6jXj
TWITTER_API_SECRET: 9ZQHvt4KrUymsGdIUFcsm0wK92VGyDZoJXFBhKrsg9K9fxSSBH

TWITTER_ACCESS_TOKEN: 24512235-m2NVYhNDpW15D4wRh6vxS7lbU5BQNwGRL7HLi80cY

TWITTER_ACCESS_TOKEN_SECRET: lrftZnWNMK1XTZtOSTYmjgqAdYyjn5SITppDBo8pPR7E8

