# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  twitter_api_key: <%= ENV["TWITTER_API_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_API_SECRET"] %>
  twitter_access_token: <%= ENV["TWITTER_ACCESS_TOKEN"] %>
  twitter_access_token_secret: <%= ENV["TWITTER_ACCESS_TOKEN_SECRET"] %>
  secret_key_base: f5d186185094a67f2006609d4d7a6115504a48310104f0aaa55463e4a93eb615d170e1cd0683ebe255a66e2e115fc78e28179f51b3f6a2478e961de48f58503a

test:
  secret_key_base: ff6d5d58ee5ded0a1486e2be5a7b8fe7c7c9ba90ff189f2c2415b7549d55159b76c76dfb1a944f2931aea9c9dfab2fb0fcdf3ca969a84ec3dcc7561fc249410e

  # Do not keep production secrets in the repository,
  # instead read values from the environment.
production:
  google_analytics_code: YOUR CODE HERE
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  twitter_api_key: <%= ENV["TWITTER_PRODUCTION_API_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_PRODUCTION_API_SECRET"] %>
  twitter_access_token: <%= ENV["TWITTER_PRODUCTION_ACCESS_TOKEN"] %>
  twitter_access_token_secret: <%= ENV["TWITTER_PRODUCTION_ACCESS_TOKEN_SECRET"] %>
  secret_key_base: f5d186185094a67f2006609d4d7a6115504a48310104f0aaa55463e4a93eb615d170e1cd0683ebe255a66e2e115fc78e28179f51b3f6a2478e961de48f58503a


